import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import styles from './layout.module.css';
import Sidebar from '@/components/navigation/Saidbar';
import Header from '@/components/header/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Rent App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <script
          crossOrigin='anonymous'
          src='//unpkg.com/react-scan/dist/auto.global.js'
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles['main-layout']}>
          <div className={styles['main-nav']}>
            <Header />
          </div>
          <aside className={styles['main-sidebar']}>
            <Sidebar />
          </aside>
          <main className={styles['main-content']}>{children}</main>
        </div>
      </body>
    </html>
  );
}
